name: Deployment Workflow

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1

  # Job 1: Deploy to Testing
  deploy-testing:
    runs-on: ubuntu-latest
    environment: testing  # Target 'testing' environment (requires manual approval)
    needs: build  # Ensures this job runs after the build job

    steps:
      - name: Deploy to Testing Environment
        run: |
          echo "Deploying to Testing Environment"
          # Add your deployment commands for testing here

  # Job 2: Deploy to Staging
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging  # Target 'staging' environment (requires manual approval)
    needs: deploy-testing  # Ensures this job runs after testing

    steps:
      - name: Deploy to Staging Environment
        run: |
          echo "Deploying to Staging Environment"
          # Add your deployment commands for staging here

  # Job 3: Deploy to Production
  deploy-production:
    runs-on: ubuntu-latest
    environment: production  # Target 'production' environment (requires manual approval)
    needs: deploy-staging  # Ensures this job runs after staging

    steps:
      - name: Deploy to Production Environment
        run: |
          echo "Deploying to Production Environment"
          # Add your deployment commands for production here
