name: Deployment Workflow

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1

      - name: Deploy to Testing (Manual Approval Required)
        environment: testing  # This triggers the manual approval in the 'testing' environment
        run: |
          echo "Deploying to Testing Environment"
          # Actual testing deployment commands here

      - name: Deploy to Staging (Manual Approval Required)
        environment: staging  # This triggers the manual approval in the 'staging' environment
        run: |
          echo "Deploying to Staging Environment"
          # Actual staging deployment commands here

      - name: Deploy to Production (Manual Approval Required)
        environment: production  # This triggers the manual approval in the 'production' environment
        run: |
          echo "Deploying to Production Environment"
          # Actual production deployment commands here
