name: ECR Login

on:
  push:
    branches:
      - main

jobs:
  ecr-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ap-south-1  # Specify your region here

      # Additional steps can go here, like building and pushing to ECR
